version: '3.8'

services:
  xvfb:
    build:
      context: ..
      dockerfile: docker/Dockerfile-xvfb
    environment:
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    cap_add:
      - SYS_ADMIN
    networks:
      - my-network
    tty: true
    healthcheck:
      test: ["CMD", "ls", "/tmp/.X11-unix/X99"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    mem_limit: 2g
    cpus: "1.5"

  emulator:
    shm_size: '1g'
    build:
      context: ..
      dockerfile: docker/Dockerfile-emulator
    ports:
      - "5554:5554"
      - "5555:5555"
      - "5037:5037"
    environment:
      - DISPLAY=:99
      - ADB_SERVER_PORT=5037
      - ADB_SERVER_SOCKET=tcp:0.0.0.0:5037
    devices:
      - "/dev/kvm:/dev/kvm"
      - "/dev/fb0:/dev/fb0"
      - "/dev/tty0:/dev/tty0"
      - "/dev/tty1:/dev/tty1"
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ${PWD}/..:/app
      - adb-shared:/adb-shared
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      xvfb:
        condition: service_healthy
    command: ./run-emulator.sh -no-host-only
    networks:
      - my-network
    mem_limit: 4g
    cpus: "2.0"
    healthcheck:
      test: ["CMD", "adb", "shell", "getprop", "sys.boot_completed"]
#      test: bash -c "unset ADB_SERVER_SOCKET && adb shell getprop sys.boot_completed && export ADB_SERVER_SOCKET=/adb-shared/adb.sock"
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 5s

  novnc:
    build:
      context: ..
      dockerfile: docker/Dockerfile-novnc
    ports:
      - "5900:5900"
      - "6080:6080"
    environment:
      - DISPLAY=:99
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      emulator:
        condition: service_healthy
    command: /app/start-server.sh
    networks:
      - my-network

  linter:
    build:
      context: ..
      dockerfile: docker/Dockerfile-common
    working_dir: /app
    command: ["ktlint"]
    networks:
      - my-network

  gradle:
    build:
      context: ..
      dockerfile: docker/Dockerfile-common
    networks:
      - my-network
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - adb-shared:/adb-shared
    environment:
      - ADB_SERVER_HOST=emulator
      - ADB_SERVER_PORT=5037
      - ADB_SERVER_SOCKET=tcp:emulator:5037
    depends_on:
      emulator:
        condition: service_healthy
    command: bash -c "export ADB_SERVER_SOCKET=tcp:emulator:5037 && adb devices && /app/gradlew -p /app installDebug --info"

  artifact-repo:
    build:
      context: ..
      dockerfile: docker/Dockerfile-artifact-repo
    volumes:
      - ${PWD}/docker/artifacts:/artifacts
    command: sleep infinity
    networks:
      - my-network

volumes:
  adb-shared:

networks:
  my-network:
    driver: bridge
