version: '3.8'

services:
  emulator:
    build:
      context: ..
      dockerfile: docker/Dockerfile-emulator
    environment:
      - DISPLAY=:1
    devices:
      - "/dev/kvm:/dev/kvm"  # Подключение KVM
    privileged: true          # Привилегированный режим для доступа к KVM
    volumes:
      - ${PWD}/..:/app
    command: ./run-emulator.sh
    networks:
      - my-network  # Подключение к пользовательской сети

  gradle:
    build:
      context: ..
      dockerfile: docker/Dockerfile-gradle
    working_dir: /app
    command: ["./gradlew", "assembleDebug"]
    networks:
      - my-network  # Подключение к пользовательской сети

  novnc:
    build:
      context: ..
      dockerfile: docker/Dockerfile-novnc
    ports:
      - "5900:5900"  # Порт для VNC
      - "6080:6080"  # Порт для noVNC
    environment:
      - DISPLAY=:0  # Убедитесь, что используется правильный дисплей
    depends_on:
      - emulator  # Зависимость от другого сервиса, например, эмулятора
    networks:
      - my-network  # Подключение к пользовательской сети

  artifact-repo:
    build:
      context: ..
      dockerfile: docker/Dockerfile-artifact-repo  # Используем Dockerfile для контейнера artifact-repo
    volumes:
      - ${PWD}/docker/artifacts:/artifacts  # Подключение каталога для хранения артефактов
    command: sleep infinity  # Поддержание контейнера запущенным для хранения артефактов
    networks:
      - my-network  # Подключение к пользовательской сети

  linter:
    build:
      context: ..
      dockerfile: docker/Dockerfile-linter
    working_dir: /app
    command: ["./gradlew", "lint"]
    networks:
      - my-network  # Подключение к пользовательской сети

networks:
  my-network:
    driver: bridge  # Использование bridge-сети
