version: '3.8'

services:
  emulator:
    build:
      context: ..
      dockerfile: docker/Dockerfile-emulator
    environment:
      - DISPLAY=:0
    devices:
      - "/dev/kvm:/dev/kvm"  # Подключение KVM
    privileged: true          # Привилегированный режим для доступа к KVM
    volumes:
      - ${PWD}/..:/app
    command: ./run-emulator.sh

  gradle:
    build:
      context: ..
      dockerfile: docker/Dockerfile-gradle
    volumes:
      - ${PWD}/..:/app
    working_dir: /app
    command: ["./gradlew", "assembleDebug"]

  novnc:
    build:
      context: ..
      dockerfile: docker/Dockerfile-novnc
    ports:
      - "5900:5900"
      - "6080:6080"
    environment:
      - DISPLAY=:0
    depends_on:
      - emulator


  artifact-repo:
    build:
      context: ..
      dockerfile: docker/Dockerfile-artifact-repo  # Используем Dockerfile для контейнера artifact-repo
    volumes:
      - ${PWD}/docker/artifacts:/artifacts  # Подключение каталога для хранения артефактов
    command: sleep infinity  # Поддержание контейнера запущенным для хранения артефактов

  linter:
    build:
      context: ..
      dockerfile: docker/Dockerfile-linter
    working_dir: /app
    command: ["./gradlew", "lint"]
