# Используем базовый образ с поддержкой JDK и Android SDK
FROM openjdk:17-jdk-slim

# Установка зависимостей и утилит
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unzip \
    git \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Установка Gradle
ENV GRADLE_VERSION=8.9
RUN curl -sL https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o gradle.zip \
    && mkdir /opt/gradle \
    && unzip gradle.zip -d /opt/gradle \
    && rm gradle.zip
ENV PATH="/opt/gradle/gradle-${GRADLE_VERSION}/bin:${PATH}"

# Установка Android Command Line Tools
ENV ANDROID_HOME=/opt/android-sdk
ENV PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}"
RUN mkdir -p ${ANDROID_HOME}/cmdline-tools \
    && curl -sL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip \
    && unzip cmdline-tools.zip -d ${ANDROID_HOME}/cmdline-tools \
    && rm cmdline-tools.zip \
    && mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest

# Установка Android SDK и инструментов
RUN yes | sdkmanager --licenses \
    && sdkmanager --update \
    && sdkmanager --install "platform-tools" \
    && sdkmanager --install "build-tools;33.0.0" \
    && sdkmanager --install "platforms;android-33"

# Установка линтеров (например, ktlint)
RUN curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.49.0/ktlint \
    && chmod +x ktlint \
    && mv ktlint /usr/local/bin/

# Копирование проекта в контейнер
WORKDIR /app
COPY . .

# Обновление Gradle wrapper до последней версии
RUN ./gradlew wrapper --gradle-version ${GRADLE_VERSION}

# Установка прав на Gradle wrapper
RUN chmod +x ./gradlew

# Установка зависимостей проекта
RUN ./gradlew dependencies

# Команда по умолчанию
CMD ["./gradlew", "tasks"]

# ENV ADB_SERVER_SOCKET=/tmp/adb/adb.sock
