# Используем базовый образ с Java и необходимыми утилитами
FROM openjdk:11

# Установка необходимых инструментов
RUN apt-get update && \
    apt-get install -y wget xvfb unzip lib32stdc++6 lib32z1 libglu1-mesa mesa-utils x11-utils

# Установка Android SDK
ENV ANDROID_SDK_ROOT=/opt/android-sdk
RUN mkdir -p $ANDROID_SDK_ROOT/cmdline-tools && \
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O /cmdline-tools.zip && \
    unzip /cmdline-tools.zip -d /tmp/cmdline-tools && \
    mv /tmp/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest && \
    rm /cmdline-tools.zip && rm -rf /tmp/cmdline-tools && \
    yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses && \
    $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

# Добавляем инструменты Android SDK в PATH
ENV PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools"

# Создаем и настраиваем эмулятор
RUN echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"

# Копируем скрипт запуска эмулятора в контейнер
COPY ./docker/run-emulator.sh ./run-emulator.sh
RUN chmod +x ./run-emulator.sh

ENV DISPLAY=:0
# Запуск эмулятора через команду
CMD ["./run-emulator.sh"]
