# Используем базовый образ с Ubuntu
FROM ubuntu:20.04

# Установка переменной окружения для предотвращения интерактивного режима
ENV DEBIAN_FRONTEND=noninteractive

# Установка зависимостей
RUN apt update && apt install -y tzdata novnc websockify x11vnc git xvfb python3 python3-pip && \
    apt-get clean

# Установка Python зависимостей
RUN pip3 install numpy

# Клонируем NoVNC
RUN git clone --branch v1.2.0 https://github.com/novnc/noVNC.git /noVNC

# Копируем ваш собственный скрипт запуска в контейнер
COPY ./docker/start-server.sh /start-server.sh

# Даем права на выполнение вашему скрипту
RUN chmod +x /start-server.sh

# Открываем нужные порты
EXPOSE 5900 6080

# Используем ваш скрипт как команду для запуска
CMD /start-server.sh
