version: '3.8'

services:
  xvfb:
    build:
      context: ..
      dockerfile: docker/Dockerfile-xvfb
    environment:
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    cap_add:
      - SYS_ADMIN
    networks:
      - my-network
    tty: true
    healthcheck:
      test: ["CMD", "ls", "/tmp/.X11-unix/X99"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    mem_limit: 2g
    cpus: "1.5"

  emulator:
    shm_size: '1g'
    build:
      context: ..
      dockerfile: docker/Dockerfile-emulator
    ports:
      - "5037:5037"
      - "5554:5554"
      - "5555:5555"
    environment:
      - DISPLAY=:99
      - ADB_SERVER_PORT=5037
#      - ADB_SERVER_SOCKET=/tmp/adb/adb.sock
    devices:
      - "/dev/kvm:/dev/kvm"
      - "/dev/fb0:/dev/fb0"
      - "/dev/tty0:/dev/tty0"
      - "/dev/tty1:/dev/tty1"
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - ${PWD}/..:/app
      - adb-data:/tmp/adb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      xvfb:
        condition: service_healthy
    command: ./run-emulator.sh
    networks:
      - my-network
    extra_hosts:
      - "emulator:172.18.0.4"
    mem_limit: 4g
    cpus: "2.0"
    healthcheck:
      test: ["CMD", "adb", "shell", "getprop", "sys.boot_completed"]
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 5s

  novnc:
    build:
      context: ..
      dockerfile: docker/Dockerfile-novnc
    ports:
      - "5900:5900"
      - "6080:6080"
    environment:
      - DISPLAY=:99
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      emulator:
        condition: service_healthy
    command: /app/start-server.sh
    networks:
      - my-network

  linter:
    build:
      context: ..
      dockerfile: docker/Dockerfile-common
    working_dir: /app
    command: ["ktlint"]
    networks:
      - my-network

  gradle:
    build:
      context: ..
      dockerfile: docker/Dockerfile-common
    working_dir: /app
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - ADB_SERVER_HOST=emulator
      - ADB_SERVER_PORT=5037
#      - ADB_SERVER_SOCKET=/tmp/adb/adb.sock
    volumes:
      - adb-data:/tmp/adb
    depends_on:
      emulator:
        condition: service_healthy
    networks:
      - my-network
    command: bash -c "adb devices && adb connect emulator:5555 && ./gradlew installDebug && sleep 300"

  artifact-repo:
    build:
      context: ..
      dockerfile: docker/Dockerfile-artifact-repo
    volumes:
      - ${PWD}/docker/artifacts:/artifacts
    command: sleep infinity
    networks:
      - my-network

volumes:
  adb-data:

networks:
  my-network:
    driver: bridge
