# Используем базовый образ Ubuntu 20.04
FROM ubuntu:20.04

# Обновляем пакеты и устанавливаем xvfb
RUN apt-get update && \
    apt-get install -y xvfb x11-apps x11-utils && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install strace

# Устанавливаем переменную окружения для дисплея
ENV DISPLAY=:0

# Добавляем команду для проверки, что Xvfb запущен
HEALTHCHECK --interval=5s --retries=5 CMD pidof Xvfb || exit 1

# Запуск Xvfb
RUN rm -rf /tmp/.X11-unix && mkdir -p /tmp/.X11-unix
CMD rm -f /tmp/.X11-unix/X* && strace -f -e trace=network -o /var/log/xvfb_strace.log Xvfb :0 -screen 0 1280x720x24 -audit 4 & tail -f /dev/null

# CMD ["Xvfb", ":0", "-screen", "0", "1280x720x24"]
