# Базовый образ Ubuntu
FROM ubuntu:24.04

# Установка переменной окружения для предотвращения интерактивного режима
ENV DEBIAN_FRONTEND=noninteractive

# Настройка временной зоны
RUN apt update && apt install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Установка необходимых инструментов и библиотек
RUN apt update && apt install -y \
    wget \
    unzip \
    openjdk-11-jdk \
    libgl1-mesa-dev \
    libqt5widgets5 \
    adb \
    lib32stdc++6 \
    lib32z1 \
    qemu-kvm \
    x11vnc \
    xvfb \
    git \
    fluxbox \
    xorg \
    openbox \
    && rm -rf /var/lib/apt/lists/*

# Установка Android SDK
ENV ANDROID_SDK_ROOT=/opt/android-sdk
ENV ANDROID_HOME=/opt/android-sdk
RUN mkdir -p $ANDROID_SDK_ROOT/cmdline-tools

# Загрузка и установка инструментов командной строки Android SDK
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /cmdline-tools.zip && \
    unzip /cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools && \
    mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest && \
    rm /cmdline-tools.zip

# Убедиться, что sdkmanager существует и имеет права на выполнение
RUN chmod +x $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager

# Установка компонентов Android SDK
RUN yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses && \
    $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

# Создание виртуального устройства AVD
RUN mkdir -p /root/.android/avd && \
    echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test_avd -k "system-images;android-30;google_apis;x86_64" --device "pixel_4"

# Настройка конфигурации AVD
RUN echo "hw.ramSize=2048" >> /root/.android/avd/test_avd.avd/config.ini && \
    echo "hw.gpu.enabled=yes" >> /root/.android/avd/test_avd.avd/config.ini && \
    echo "hw.gpu.mode=swiftshader" >> /root/.android/avd/test_avd.avd/config.ini

# Установка переменных среды и путей
ENV PATH="$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"

# Копирование скрипта запуска эмулятора
COPY ./docker/run-emulator.sh /usr/local/bin/run-emulator.sh
RUN chmod +x /usr/local/bin/run-emulator.sh

# Открытие необходимых портов для эмулятора и noVNC
EXPOSE 5554 5555 5900 6080

# Команда по умолчанию для запуска скрипта
CMD ["/usr/local/bin/run-emulator.sh"]
