# Dockerfile-emulator
FROM ubuntu:24.04

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    openjdk-11-jdk \
    wget \
    unzip \
    qemu-kvm \
    libvirt-bin \
    virtinst \
    bridge-utils \
    x11vnc \
    xvfb \
    git \
    android-sdk \
    && rm -rf /var/lib/apt/lists/*

# Установка Android SDK
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O /tmp/cmdline-tools.zip \
    && mkdir -p /android/cmdline-tools \
    && unzip /tmp/cmdline-tools.zip -d /android/cmdline-tools \
    && rm /tmp/cmdline-tools.zip

ENV ANDROID_HOME /android
ENV PATH ${PATH}:${ANDROID_HOME}/cmdline-tools/bin:${ANDROID_HOME}/platform-tools

# Пример запуска эмулятора
RUN sdkmanager --licenses
RUN sdkmanager "platform-tools" "system-images;android-30;google_apis;x86_64" "emulator"

# Копирование скрипта запуска эмулятора
COPY ./run-emulator.sh /app/run-emulator.sh
RUN chmod +x /app/run-emulator.sh

# Команда для запуска эмулятора
CMD ["/app/run-emulator.sh"]
