# Используем базовый образ с JDK
FROM openjdk:11-jdk-slim

# Устанавливаем необходимые пакеты
RUN apt-get update && apt-get install -y wget unzip novnc websockify && \
    rm -rf /var/lib/apt/lists/*

# Скачиваем и распаковываем Gradle
ENV GRADLE_VERSION=7.4.2
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -P /tmp && \
    unzip -d /opt/gradle /tmp/gradle-${GRADLE_VERSION}-bin.zip && \
    rm /tmp/gradle-${GRADLE_VERSION}-bin.zip

# Добавляем Gradle в PATH
ENV GRADLE_HOME=/opt/gradle/gradle-${GRADLE_VERSION}
ENV PATH="${GRADLE_HOME}/bin:${PATH}"

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем проектные файлы
COPY . /app

# Создаём gradlew, если его нет, и устанавливаем права на выполнение
RUN if [ ! -f "./gradlew" ]; then gradle wrapper --gradle-version ${GRADLE_VERSION}; fi && \
    chmod +x ./gradlew

# Запускаем Gradle сборку
CMD ["./gradlew", "build"]
