FROM ubuntu:20.04

# Установка переменной окружения для предотвращения интерактивного режима
ENV DEBIAN_FRONTEND=noninteractive

# Настройка временной зоны
RUN apt update && apt install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Установка необходимых зависимостей для хранилища артефактов
RUN apt update && apt install -y \
    nginx \
    && rm -rf /var/lib/apt/lists/*

# Конфигурация хранилища артефактов (например, для Nexus или просто папки)
RUN mkdir -p /artifacts

# Настройка Nginx для обслуживания артефактов
COPY ./docker/nginx.conf /etc/nginx/nginx.conf

# Указываем команду для запуска Nginx
CMD ["nginx", "-g", "daemon off;"]
