apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/domdom/ProjectNIASPO
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
