name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.0
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Debug project structure
        run: |
          echo "Project root:"
          ls -la
          echo "Docker directory:"
          ls -la ./docker

      - name: Build Docker images
        working-directory: ./docker
        run: |
          docker compose build

      - name: Start emulator and services
        working-directory: ./docker
        run: |
          docker compose up -d xvfb emulator novnc

      - name: Wait for emulator health check
        working-directory: ./docker
        run: |
          while [ "$(docker inspect --format='{{json .State.Health.Status}}' $(docker compose ps -q emulator))" != "\"healthy\"" ]; do
            echo "Waiting for emulator to become healthy..."
            sleep 10
          done

      - name: Run linter
        working-directory: ./docker
        run: |
          docker compose run --rm linter

      - name: Run tests
        working-directory: ./docker
        run: |
          docker compose run --rm gradle

      - name: Collect artifacts
        working-directory: ./docker
        run: |
          mkdir -p artifacts
          docker compose run --rm artifact-repo cp -r /artifacts/* ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./docker/artifacts

      - name: Clean up
        working-directory: ./docker
        run: |
          docker compose down -v
