name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Шаг 3: Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 4: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 5: Сборка Docker Compose
      - name: Build Docker Compose services
        run: docker-compose -f docker/docker-compose.yml build --no-cache --progress=plain

      # Шаг 6: Запуск контейнеров
      - name: Start Docker Compose
        run: docker-compose -f docker/docker-compose.yml up -d

      # Шаг 7: Ожидание запуска эмулятора
      - name: Wait for emulator to be ready
        run: |
          for i in {1..10}; do
            if docker-compose logs emulator | grep -q "Boot completed"; then
              echo "Emulator is ready.";
              exit 0;
            fi;
            sleep 10;
          done;
          echo "Emulator failed to start.";
          exit 1;

      # Шаг 8: Сборка Gradle проекта
      - name: Build with Gradle
        run: |
          docker-compose exec gradle /bin/bash -c "./gradlew assembleDebug"

      # Шаг 9: Запуск линтера
      - name: Run Linter
        run: |
          docker-compose exec linter ktlint

      # Шаг 10: Тесты на Android эмуляторе
      - name: Run Android Emulator Tests
        run: |
          docker-compose exec emulator /bin/bash -c "./run-emulator-tests.sh"

      # Шаг 11: Диагностика логов
      - name: Debug emulator logs
        run: docker-compose logs emulator

      # Шаг 12: Остановка сервисов
      - name: Stop Docker Compose services
        run: docker-compose -f docker/docker-compose.yml down
