name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Запуск контейнеров через Docker Compose
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2

    - name: Start services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        # Задержка для инициализации контейнеров
        sleep 30

    - name: Run Gradle Build
      run: |
        docker exec -t gradle-container /bin/bash -c "./gradlew assembleDebug"

    - name: Run Android Emulator Tests
      run: |
        docker exec -t emulator-container /bin/bash -c "./run-emulator-tests.sh"

    - name: Stop Docker Compose services
      run: docker-compose down
