name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Start services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        sleep 30

    - name: Run Gradle Build
      run: |
        docker exec -t gradle-container /bin/bash -c "./gradlew assembleDebug"

    - name: Run Android Emulator Tests
      run: |
        docker exec -t emulator-container /bin/bash -c "./run-emulator-tests.sh"

    - name: Stop Docker Compose services
      run: docker-compose down
