name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Шаг 3: Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 4: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 5: Сборка и запуск контейнеров
      - name: Start Docker Compose
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build
          sleep 30

      # Шаг 6: Сборка Gradle проекта
      - name: Build with Gradle
        run: |
          docker-compose exec gradle /bin/bash -c "./gradlew assembleDebug"

      # Шаг 7: Запуск линтера
      - name: Run Linter
        run: |
          docker-compose exec linter ktlint

      # Шаг 8: Тесты на Android эмуляторе
      - name: Run Android Emulator Tests
        run: |
          docker-compose exec emulator /bin/bash -c "./run-emulator-tests.sh"

      # Шаг 9: Остановка сервисов
      - name: Stop Docker Compose services
        run: docker-compose -f docker/docker-compose.yml down
